# Generated by Django 5.1.5 on 2025-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='dest_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='src_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
